git-debimport libcgroup_0.41.orig.tar.xz

diff --git a/scripts/init.d/cgconfig.in b/scripts/init.d/cgconfig.in
--- a/scripts/init.d/cgconfig.in
+++ b/scripts/init.d/cgconfig.in
@@ -23,23 +23,18 @@
 # Provides:             cgconfig
 # Required-Start:
 # Required-Stop:
-# Should-Start:
-# Should-Stop:
-# Short-Description:    start and stop the WLM configuration
-# Description:          This script allows us to create a default configuration
+# Should-Start:         ypbind
+# Should-Stop:          ypbind
+# Short-Description:    Create and setup control group filesystem(s)
+# Description:          Create and setup control group filesystem(s)
 ### END INIT INFO
 
 # get correct location of binaries from configure
 prefix=@prefix@;exec_prefix=@exec_prefix@;sbindir=@sbindir@
 CGCONFIGPARSER_BIN=$sbindir/cgconfigparser
-CGROUP_FS=cgroup
 CONFIG_FILE=/etc/cgconfig.conf
-
-# support multiple mount points
-declare -a MOUNTPOINT
-declare -a MOUNTOPTS
-maxindex=0
 servicename=cgconfig
+lockfile=/var/lock/subsys/$servicename
 
 #
 # Source LSB routines
@@ -53,14 +48,12 @@ if [ -e /etc/sysconfig/cgconfig ]; then
 fi
 
 create_default_groups() {
-        declare defaultcgroup
+	defaultcgroup=
 
-        if [ -f /etc/cgrules.conf ]
-        then
-            read user ctrl defaultcgroup <<< \
-		`grep -m1 '^\*[[:space:]]\+' /etc/cgrules.conf`
-            if [[ -n $defaultcgroup && $defaultcgroup = "*" ]]
-            then
+        if [ -f /etc/cgrules.conf ]; then
+	    read user ctrl defaultcgroup <<< \
+		    $(grep -m1 '^\*[[:space:]]\+' /etc/cgrules.conf)
+            if [ -n "$defaultcgroup" -a "$defaultcgroup" = "*" ]; then
                 log_warning_msg "/etc/cgrules.conf incorrect"
                 log_warning_msg "Overriding it"
                 defaultcgroup=
@@ -82,7 +75,7 @@ create_default_groups() {
         # Create the default group, ignore errors when the default group
         # already exists.
         #
-        cgcreate -g $controllers:$defaultcgroup 2>/dev/null
+        cgcreate -f 664 -d 775 -g $controllers:$defaultcgroup 2>/dev/null
 
         #
         # special rule for cpusets
@@ -104,33 +97,34 @@ create_default_groups() {
 
 start() {
         echo -n "Starting cgconfig service: "
-	if [ -f /var/lock/subsys/$servicename ]
-        then
+	if [ -f "$lockfile" ]; then
             log_warning_msg "lock file already exists"
-            return
+            return 0
         fi
 
-        if [ $? -eq 0 ]
-        then
+        if [ $? -eq 0 ]; then
+                if [ ! -s $CONFIG_FILE ]; then
+                    log_failure_msg $CONFIG_FILE "is not configured"
+                    return 6
+                fi
+
                 $CGCONFIGPARSER_BIN -l $CONFIG_FILE
                 retval=$?
-                if [ $retval -ne 0 ]
-                then
+                if [ $retval -ne 0 ]; then
                     log_failure_msg "Failed to parse " $CONFIG_FILE
-                    return $retval
+                    return 1
                 fi
         fi
 
-        if [ $CREATE_DEFAULT == "yes" ]; then
+        if [ $CREATE_DEFAULT = "yes" ]; then
                 create_default_groups
         fi
 
-        touch /var/lock/subsys/$servicename
+        touch "$lockfile"
         retval=$?
-        if [ $retval -ne 0 ]
-        then
-            log_failure_msg "Failed to touch " /var/lock/subsys/$servicename
-            return $retval
+        if [ $retval -ne 0 ]; then
+            log_failure_msg "Failed to touch $lockfile"
+            return 1
         fi
         log_success_msg
         return 0
@@ -139,8 +133,9 @@ start() {
 stop() {
     echo -n "Stopping cgconfig service: "
     cgclear
-    rm -f /var/lock/subsys/$servicename
+    rm -f "$lockfile"
     log_success_msg
+    return 0
 }
 
 trapped() {
@@ -152,7 +147,7 @@ trapped() {
 
 usage() {
     echo "$0 <start|stop|restart|condrestart|status>"
-    exit 1
+    exit 2
 }
 
 common() {
@@ -165,39 +160,47 @@ common() {
     trap "trapped INT"   INT
 }
 
+restart() {
+	common
+	stop
+	start
+}
+
+RETVAL=0
+
 case $1 in
     'stop')
         common
-        stop;
+        stop
+        RETVAL=$?
         ;;
     'start')
         common
-        start;
-        ;;
-    'restart')
-        common
-	stop
         start
+        RETVAL=$?
         ;;
-    'reload')
-        common
-	stop
-        start
+    'restart'|'reload')
+	restart
+        RETVAL=$?
         ;;
     'condrestart')
-        if [ -f /var/lock/subsys/$servicename ] ; then
-            stop
-            start
+        if [ -f "$lockfile" ]; then
+            restart
+            RETVAL=$?
         fi
         ;;
     'status')
-        if [ -f /var/lock/subsys/$servicename ] ; then
+        if [ -f "$lockfile" ]; then
             echo "Running"
+            exit 0
         else
             echo "Stopped"
+            exit 3
         fi
 	;;
     *)
         usage
         ;;
 esac
+
+exit $RETVAL
diff --git a/scripts/init.d/cgred.in b/scripts/init.d/cgred.in
--- a/scripts/init.d/cgred.in
+++ b/scripts/init.d/cgred.in
@@ -34,6 +34,7 @@
 
 prefix=@prefix@;exec_prefix=@exec_prefix@;sbindir=@sbindir@
 CGRED_BIN=$sbindir/cgrulesengd
+CGRED_CONF=/etc/cgrules.conf
 
 # Sanity checks
 [ -x $CGRED_BIN ] || exit 1
@@ -47,7 +48,13 @@ if [ -f "/etc/sysconfig/cgred.conf" ] ; then
 	. /etc/sysconfig/cgred.conf
 	OPTIONS="$NODAEMON $LOG"
 	if [ -n "$LOG_FILE" ]; then
-		OPTIONS="$OPTIONS --log-file=$LOG_FILE"
+		OPTIONS="$OPTIONS --logfile=$LOG_FILE"
+	fi
+	if [ -n "$SOCKET_USER" ]; then
+		OPTIONS="$OPTIONS -u $SOCKET_USER"
+	fi
+	if [ -n "$SOCKET_GROUP" ]; then
+		OPTIONS="$OPTIONS -g $SOCKET_GROUP"
 	fi
 else
 	OPTIONS=""
@@ -56,61 +63,83 @@ fi
 # For convenience
 processname=cgrulesengd
 servicename=cgred
+lockfile="/var/lock/subsys/$servicename"
 pidfile=/var/run/cgred.pid
-
-RETVAL=0
 
 start()
 {
-	echo $"Starting CGroup Rules Engine Daemon..."
-	if [ -f "/var/lock/subsys/$servicename" ] ; then
+	echo -n $"Starting CGroup Rules Engine Daemon: "
+	if [ -f "$lockfile" ]; then
 		log_failure_msg "$servicename is already running with PID `cat ${pidfile}`"
+		return 0
+	fi
+	num=`grep "cgroup" /proc/mounts | awk '$3=="cgroup"' | wc -l`
+	if [ $num -eq 0 ]; then
+		echo
+		log_failure_msg $"Cannot find cgroups, is cgconfig service running?"
 		return 1
 	fi
 	daemon --check $servicename --pidfile $pidfile $CGRED_BIN $OPTIONS
-	RETVAL=$?
+	retval=$?
 	echo
-	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$servicename
+	if [ $retval -ne 0 ]; then
+		return 7
+	fi
+	touch "$lockfile"
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
 	echo "`pidof $processname`" > $pidfile
+	return 0
 }
 
 stop()
 {
 	echo -n $"Stopping CGroup Rules Engine Daemon..."
-	killproc -p $pidfile $processname -TERM
-	RETVAL=$?
-	echo
-	if [ $RETVAL -eq 0 ] ; then
-		rm -f /var/lock/subsys/$servicename
-		rm -f $pidfile
+	if [ ! -f $pidfile ]; then
+		log_success_msg
+		return 0
 	fi
-	log_success_msg
+	killproc -p $pidfile -TERM "$processname"
+	retval=$?
+	echo
+	if [ $retval -ne 0 ]; then
+		return 1
+	fi
+	rm -f "$lockfile" "$pidfile"
+	return 0
 }
+
+RETVAL=0
 
 # See how we are called
 case "$1" in
 	start)
 		start
+		RETVAL=$?
 		;;
 	stop)
 		stop
+		RETVAL=$?
 		;;
 	status)
-		status -p $pidfile $processname
+		status -p $pidfile $servicename
 		RETVAL=$?
 		;;
 	restart)
 		stop
 		start
+		RETVAL=$?
 		;;
 	condrestart)
-		if [ -f /var/lock/subsys/$servicename ] ; then
+		if [ -f "$lockfile" ]; then
 			stop
 			start
+			RETVAL=$?
 		fi
 		;;
 	reload|flash)
-		if [ -f /var/lock/subsys/$servicename ] ; then
+		if [ -f "$lockfile" ]; then
 			echo $"Reloading rules configuration..."
 			kill -s 12 `cat ${pidfile}`
 			RETVAL=$?
@@ -125,6 +154,7 @@ case "$1" in
 		;;
 	*)
 		echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
+		RETVAL=2
 		;;
 esac
 
